package aeb.proyecto.room.dao

import aeb.proyecto.room.entities.Habit
import aeb.proyecto.room.entities.HabitDay
import aeb.proyecto.room.entities.HabitNotification
import aeb.proyecto.room.entities.relations.EntireHabit
import aeb.proyecto.room.model.NotificationWithNameAndColor
import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Transaction


/**
 * Enterprise-level Data Access Object (DAO) orchestrating complex relational database transactions
 * across the holistic habit tracking graph.
 *
 * Implements atomic persistence mechanisms, precise tabular multi-joins, and reactive database
 * streaming capabilities to synchronize [Habit], [HabitDay], and [HabitNotification] states.
 */
@Dao
interface EntireHabitDao {

    /**
     * Inserts a baseline [Habit] configuration metadata entry into the persistent layer.
     *
     * @param habit The structural core entity container.
     * @return The autogenerated unique primary key [Long] identifier assigned by SQLite.
     */
    @Insert
    fun insertHabit(habit: Habit):Long

    /**
     * Persists a collection of localized historical execution logs bound to a specific habit timeline.
     *
     * @param dailyHabit The batch collection of [HabitDay] records to append.
     */
    @Insert
    fun insertDailyHabits(dailyHabit: List<HabitDay>)

    /**
     * Configures a batch of scheduled broadcast reminder actions inside the localized tracking index.
     *
     * @param notification The collection of [HabitNotification] alert properties to register.
     */
    @Insert
    fun insertNotification(notification: List<HabitNotification>)

    /**
     * Executes an inner join across alert configurations and active habit identities to yield flat
     * projections tailored specifically for system [AlarmManager] registrations.
     *
     * @return A flat [List] containing custom projection matrix objects.
     */
    @Query("""
        SELECT HABITNOTIFICATION.id AS id, HABITNOTIFICATION.time AS time, Habit.name AS name, Habit.color AS color,
        HABITNOTIFICATION.type AS typeNotification
        FROM HABITNOTIFICATION
        INNER JOIN Habit ON HABITNOTIFICATION.habitId = Habit.id
    """)
    fun getAllNotifications():List<NotificationWithNameAndColor>

    /**
     * Triggers a destructive database wipe clearing out all existing [Habit] rows.
     * Cascading rules automatically purge matching relational logs and alerts.
     */
    @Query("DELETE FROM Habit")
    fun deleteHabits()

    /**
     * Emits a list where return every habit in the bbdd
     *
     * Marked with [@Transaction] to guarantee that fetching the core metadata alongside nested logs
     * and alerts stays strictly isolated and consistent. Room automatically emits a newly hydrated
     * list whenever any downstream database mutative write occurs.
     *
     * @return A reactive stream wrapping the hierarchical aggregate collection.
     */
    @Transaction
    @Query("SELECT * FROM Habit")
    fun getAll():List<EntireHabit>

    /**
     * Atomic synchronization procedure that clears out legacy state configurations and populates
     * the relational database with an updated master graph snapshot.
     *
     * Operates completely inside a single SQLite transaction wrapper, guaranteeing full atomic rollback
     * safety on upstream failure vectors and returns fresh metadata required to rebuild device alerts.
     *
     * @param data The updated upstream master collection tracking the consolidated entity state tree.
     * @return An updated, projection list targeted directly at immediate device alarm scheduler rebuilds.
     */
    @Transaction
    fun setData(data:List<EntireHabit>):List<NotificationWithNameAndColor>{
        // Step 1: Wipe all stale configuration histories
        deleteHabits()

        // Step 2: Iterate and reconstruct the relational graph sequentially
        data.forEach { habitComplete ->
            // Insert core entity and extract the newly provisioned database identity key
            val id = insertHabit(habitComplete.habit)

            // Map the provisioned relational foreign key onto the tracking day logs and insert
            val dailyHabits = habitComplete.dailyHabits.map { dailyHabit -> dailyHabit.copy(idHabit = id) }
            insertDailyHabits(dailyHabits)

            // Map the provisioned relational foreign key onto the notification profiles and insert
            val notificationsHabit = habitComplete.notifications.map { notification -> notification.copy(habitId = id) }
            insertNotification(notificationsHabit)
        }

        // Step 3: Extract fresh, clean projections for background workers
        return getAllNotifications()
    }
}