package aeb.proyecto.room.dao

import aeb.proyecto.room.entities.HabitDay
import aeb.proyecto.room.entities.Habit
import aeb.proyecto.room.entities.relations.HabitWithDailyHabit
import aeb.proyecto.room.model.classes.TypeHabit
import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Update
import kotlinx.coroutines.flow.Flow
import java.time.LocalDate

/**
 * Core Data Access Object (DAO) managing daily execution streams, relational graph queries,
 * and granular lifecycle mutations for the habit ecosystem.
 *
 * Provides extensive reactive [Flow] queries to feed the Jetpack Compose user interface
 * with real-time persistence updates upon any downstream table mutation.
 */
@Dao
interface HabitWithDailyHabitDao {

    /**
     * Persists a core [Habit] configuration target.
     *
     * @param habit The structural core entity model.
     * @return The autogenerated unique primary key [Long] allocated by SQLite.
     */
    @Insert
    fun insertHabit(habit: Habit):Long

    /**
     * Appends a new localized historical completion log [HabitDay] entry.
     *
     * @param dailyHabit The metric progress record bound to a specific calendar date.
     * @return The unique tracking row [Long] identifier inside the local cache.
     */
    @Insert
    fun insertDailyHabit(dailyHabit: HabitDay):Long

    /**
     * Updates an existing [HabitDay] localized completion or quantitative logging metric.
     *
     * @param dailyHabit The updated tracking day log containing matching primary keys.
     */
    @Update
    fun updateDailyHabit(dailyHabit: HabitDay)

    /**
     * Modifies the core configuration attributes (name, color, cadence) of an existing [Habit].
     *
     * @param habit The updated blueprint state containing matching primary keys.
     */
    @Update
    fun updateHabit(habit: Habit)

    /**
     * Streams the entire collection of raw baseline [Habit] rows present in the cache.
     *
     * @return A cold, reactive [Flow] emitting updated lists upon any structural modification.
     */
    @Query("SELECT * FROM Habit")
    fun getAllHabits():Flow<List<Habit>>

    /**
     * Performs a synchronous, snapshot-based fetch of all historical log records matching a target habit identifier.
     *
     * @param id The primary foreign key pointer targeting the parent habit.
     * @return A flat [List] containing all corresponding [HabitDay] logs.
     */
    @Query("SELECT * FROM HabitDay WHERE idHabit = :id")
    fun getDailyHabits(id:Long):List<HabitDay>

    /**
     * Destroys a [Habit] row from the registry using its unique identifier.
     * Relational cascading rules configured at the SQLite schema level handle child purges.
     *
     * Encapsulated inside a [@Transaction] to guarantee thread isolation during destructive cascades.
     *
     * @param habitId The unique primary key targeting the row to drop.
     */
    @Transaction
    @Query("DELETE FROM Habit WHERE id = :habitId")
    fun deleteHabit(habitId: Long)

    /**
     * Streams the complete relational aggregate tree combining habits alongside their nested historical tracking days.
     *
     * Marked with [@Transaction] to safely isolate multitable queries under a coherent snapshot view.
     *
     * @return A reactive stream of the hydrated [HabitWithDailyHabit] relational framework graph.
     */
    @Transaction
    @Query("SELECT * FROM HABIT")
    fun getHabits(): Flow<List<HabitWithDailyHabit>>

    /**
     * Streams a singular, highly isolated relational aggregate branch matching a specific database identity key.
     *
     * @param id The unique primary key targeting the entity.
     * @return A reactive stream emitting the hydrated relation wrapper, or null if the target does not exist.
     */
    @Transaction
    @Query("SELECT * FROM HABIT where id = :id")
    fun getHabitWithDailyHabits(id:Long): Flow<HabitWithDailyHabit?>

    /**
     * Extracts a unique list of all habit cadence types currently active across the user's registry.
     * Useful for building dynamic category filters inside dashboard components.
     *
     * @return A cold [Flow] tracking unique [TypeHabit] configurations.
     */
    @Query("SELECT DISTINCT typeHabit FROM Habit")
    fun getExistingTypesHabit():Flow<List<TypeHabit>>

    /**
     * Streams all completion logs recorded across the entire global ecosystem within a specific calendar range.
     * Tailored for feeding comprehensive system-wide performance dashboard charts.
     *
     * @param startDate The lower bounds inclusive calendar fence.
     * @param endDate The upper bounds inclusive calendar fence.
     * @return A reactive stream containing matching [HabitDay] entities.
     */
    @Query("SELECT * FROM HabitDay WHERE date BETWEEN :startDate AND :endDate")
    fun getDailyHabitsByDateRange(startDate: LocalDate, endDate: LocalDate): Flow<List<HabitDay>>

    /**
     * Streams completion logs recorded for a specific isolated habit within a targeted calendar range window.
     *
     * @param id The unique parent foreign key identifier.
     * @param startDate The lower bounds inclusive calendar fence.
     * @param endDate The upper bounds inclusive calendar fence.
     * @return A reactive stream containing matching scoped [HabitDay] entries.
     */
    @Query("SELECT * FROM HabitDay WHERE date BETWEEN :startDate AND :endDate AND idHabit = :id")
    fun getDailyHabitsByDateRangeById(id:Long, startDate: LocalDate, endDate: LocalDate): Flow<List<HabitDay>>

    /**
     * Performs a synchronized lookup for an exact, isolated tracking day entry bound to a specific date and habit slot.
     *
     * @param date The exact calendar day coordinate.
     * @param idHabit The target parent foreign key identifier.
     * @return The matched [HabitDay] snapshot record, or null if no entry exists for that explicit grid space.
     */
    @Query("SELECT * FROM HabitDay WHERE date = :date AND idHabit = :idHabit")
    fun getHabitDay(date: LocalDate, idHabit: Long): HabitDay?

    /**
     * Synchronous snapshot lookup fetching a raw [Habit] metadata row. Expected to throw if missing.
     *
     * @param id The unique primary key identifier.
     * @return The targeted [Habit] core entity configuration model.
     */
    @Query("SELECT * FROM Habit WHERE id = :id")
    fun getHabit(id:Long):Habit

    /**
     * Reactive stream tracking an isolated [Habit] configuration row. Safe against external deletions.
     *
     * @param id The unique primary key identifier.
     * @return A dynamic [Flow] emitting state changes or null if dropped upstream.
     */
    @Query("SELECT * FROM Habit WHERE id = :id")
    fun getHabitFlow(id:Long): Flow<Habit?>

    /**
     * Synchronous defensive lookup fetching a raw [Habit] profile. Returns null safely if unallocated.
     *
     * @param id The unique primary key identifier.
     * @return The matched [Habit] configuration model, or null if no matching row is present.
     */
    @Query("SELECT * FROM Habit WHERE id = :id")
    fun getHabitOrNull(id:Long):Habit?

    /**
     * Hard drops an isolated [HabitDay] tracking cell mapping to a specific date vector.
     *
     * @param id The unique parent foreign key identifier.
     * @param date The exact targeted log date matrix to wipe.
     */
    @Query("DELETE FROM HABITDAY where idHabit = :id AND date = :date")
    fun deleteHabitDay(id:Long,date:LocalDate)

    /**
     * Synchronous lookup extracting a tracking log cell matching an explicit calendar checkpoint.
     *
     * @param id The unique parent foreign key identifier.
     * @param date The localized calendar date target vector.
     * @return The structural tracking log [HabitDay] container, or null if unallocated.
     */
    @Query("SELECT * FROM HabitDay WHERE date = :date AND idHabit = :id")
    fun getDayByDate(id:Long, date:LocalDate): HabitDay?
}