package aeb.proyecto.room.dao

import aeb.proyecto.room.entities.Habit
import aeb.proyecto.room.entities.HabitNotification
import aeb.proyecto.room.entities.relations.HabitWithNotification
import aeb.proyecto.room.model.NotificationWithNameAndColor
import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Transaction
import androidx.room.Update

/**
 * Specialized Data Access Object (DAO) orchestrating structural interactions and scheduled
 * broadcast reminder alerts bound to specific habit entities.
 *
 * Implements atomic transactional wrappers to manage complex one-to-many (1:N) lifecycles,
 * powering dynamic local notification scheduling loops.
 */
@Dao
interface HabitWithNotificationDao {

    /**
     * Appends a batch of scheduled [HabitNotification] alert properties into the local storage layer.
     *
     * @param notification The collection of notification configuration records to register.
     */
    @Insert
    fun insertNotifications(notification: List<HabitNotification>)

    /**
     * Persists a baseline [Habit] configuration target.
     *
     * @param habit The structural core entity model.
     * @return The autogenerated unique primary key [Long] allocated by SQLite.
     */
    @Insert
    fun insertHabit(habit: Habit):Long

    /**
     * Modifies the core configuration attributes of an existing [Habit] row.
     *
     * @param habit The updated blueprint state containing matching primary keys.
     */
    @Update
    fun updateHabit(habit: Habit)

    /**
     * Modifies a batch collection of active [HabitNotification] rows.
     *
     * @param notification The collection of alert profiles containing matching primary keys.
     */
    @Update
    fun updateNotification(notification: List<HabitNotification>)

    /**
     * Executes an inner join across alert configurations and active habit identities, filtered
     * by a single parent handle, to yield isolated flat projections tailored for [AlarmManager] updates.
     *
     * @param id The unique parent primary key identifier.
     * @return A flat [List] containing custom projection matrix objects matching the targeted habit.
     */
    @Query("""
        SELECT HABITNOTIFICATION.id AS id, HABITNOTIFICATION.time AS time, Habit.name AS name, Habit.color AS color,
        HABITNOTIFICATION.type AS typeNotification
        FROM HABITNOTIFICATION
        INNER JOIN Habit ON HABITNOTIFICATION.habitId = Habit.id
        WHERE Habit.id = :id
    """)
    fun getAllNotificationsWithId(id:Long):List<NotificationWithNameAndColor>

    /**
     * Purges all active [HabitNotification] tracking rows bound to a specific parent habit handle.
     *
     * @param id The target parent foreign key identifier.
     */
    @Query("DELETE FROM HABITNOTIFICATION WHERE habitId = :id")
    fun deleteNotifications(id:Long)

    /**
     * Snapshot lookup fetching all raw, non-joined [HabitNotification] configuration items matching a target parent.
     *
     * @param id The target parent foreign key identifier.
     * @return A flat [List] containing the corresponding raw entities.
     */
    @Query("SELECT * FROM HABITNOTIFICATION where habitId = :id")
    fun getNotificationById(id:Long):List<HabitNotification>

    /**
     * Aggregates a full relational data branch combining the parent habit alongside its child reminders.
     *
     * Encapsulated inside a [@Transaction] to guarantee transactional state consistency.
     *
     * @param habitId The unique primary key handle targeting the source habit.
     * @return The fully hydrated [HabitWithNotification] relational framework entity wrapper.
     */
    @Transaction
    @Query("SELECT * FROM Habit WHERE id = :habitId")
    fun getHabitById(habitId: Long): HabitWithNotification

    /**
     * Atomic persistence transaction that registers a brand new habit alongside its attached list
     * of alert reminders in a single operation.
     *
     * Extracts the newly generated identity key to correctly bridge the child entities foreign key constraint.
     *
     * @param habitWithNotification The relational compound aggregate structure to persist.
     * @return The autogenerated master [Long] identity assigned to the root habit.
     */
    @Transaction
    fun saveHabit(habitWithNotification: HabitWithNotification):Long{
        val id = insertHabit(habitWithNotification.habit)

        if (habitWithNotification.notifications.isNotEmpty()) {
            insertNotifications(habitWithNotification.notifications.map { it.copy(habitId = id) })
        }

        return id
    }

    /**
     * Atomic updating transaction that updates a habit's configurations and overrides its reminder sub-graph.
     *
     * Leverages a destructive "Wipe & Re-insert" sub-pipeline to safely synchronize the children rows
     * without producing legacy or orphaned records inside the SQLite database structure.
     *
     * @param habitWithNotification The relational compound aggregate structure containing the updated states.
     * @return The immutable primary key handle [Long] identifying the modified habit entity tree.
     */
    @Transaction
    fun updateHabit(habitWithNotification: HabitWithNotification):Long{
        val id = habitWithNotification.habit.id
        updateHabit(habitWithNotification.habit)

        deleteNotifications(habitWithNotification.habit.id)

        if (habitWithNotification.notifications.isNotEmpty()) {
            insertNotifications(habitWithNotification.notifications.map { it.copy(habitId = id) })
        }

        return id
    }
}