package aeb.proyecto.room.dao

import aeb.proyecto.room.entities.TimeEntry
import aeb.proyecto.room.entities.relations.TimeEntryWithHabit
import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Update
import kotlinx.coroutines.flow.Flow
import java.time.LocalDate
import java.time.LocalDateTime

/**
 * Data Access Object (DAO) orchestrating persistence for time tracking instruments.
 *
 * Manages states, filters, and history matrices across three temporal modalities (Stopwatch,
 * Countdown Timer, and Interval Counters) leveraging dynamic defensive queries and flat analytical multi-joins.
 */
@Dao
interface TimerEntryDao {

    /**
     * Persists a newly created [TimeEntry] configuration record.
     *
     * @param timerEntry The structural state snapshot monitoring timer configurations.
     * @return The autogenerated unique primary key [Long] allocated by SQLite.
     */
    @Insert
    fun insertTimerEntry(timerEntry: TimeEntry): Long

    /**
     * Modifies the parameters or tracking flags of an existing [TimeEntry] row.
     *
     * @param timerEntry The updated tracking snapshot containing matching primary keys.
     */
    @Update
    fun updateTimerEntry(timerEntry: TimeEntry)

    /**
     * Searches for an existing active Stopwatch configuration (typeTimer = 0).
     *
     * Features full null-safe bridging logic to match entries that are either completely global
     * or strictly bound to a target habit identity.
     *
     * @param idHabit The optional unique foreign key handle targeting a parent habit.
     * @return The matched [TimeEntry] row, or null if no stopwatch layout fits the criteria.
     */
    @Query(
        """
        Select * from TIMEENTRY where typeTimer = 0
              AND (
            (:idHabit IS NULL AND idHabit IS NULL) OR 
            (idHabit = :idHabit)
          )
            """
    )
    fun findStopWatch(idHabit: Long?): TimeEntry?

    /**
     * Searches for a specific matching standalone Countdown Timer configuration (typeTimer = 1).
     *
     * @param time The primary target volume duration scalar mapped in raw seconds.
     * @param idHabit The optional unique foreign key handle targeting a parent habit.
     * @return The matched single [TimeEntry] row container, or null if unallocated.
     */
    @Query(
        """
    SELECT * FROM TIMEENTRY 
    WHERE typeTimer = 1 
      AND time = :time 
      AND (
            (:idHabit IS NULL AND idHabit IS NULL) OR 
            (idHabit = :idHabit)
          )
    LIMIT 1
    """
    )
    fun findTimer(time: Long, idHabit: Long?): TimeEntry?

    /**
     * Searches for an exact complex dynamic Interval/Tabata configuration matrix (typeTimer = 2).
     *
     * @param time The primary active work segment duration mapped in seconds.
     * @param rest The auxiliary cooldown rest segment duration mapped in seconds.
     * @param interval The aggregate targeted iterations count loop multiplier.
     * @param idHabit The optional unique foreign key handle targeting a parent habit.
     * @return The matched structural [TimeEntry] template row, or null if unallocated.
     */
    @Query(
        """
        Select * from TIMEENTRY where typeTimer = 2      
            AND (
            (:idHabit IS NULL AND idHabit IS NULL) OR 
            (idHabit = :idHabit)
            ) 
            AND time = :time 
            AND restTime = :rest 
            AND intervals = :interval LIMIT 1
    """
    )
    fun findInterval(time: Long, rest: Long, interval: Long, idHabit: Long?): TimeEntry?

    /**
     * Streams all tracking configurations actively bookmarked as system favorites by the user.
     *
     * Performs a clear analytical flat LEFT JOIN to resolve attached [Habit] properties
     * while preserving free global timers, ordering by freshest interaction timelines.
     *
     * @return A cold, reactive [Flow] tracking matching [TimeEntryWithHabit] relational items.
     */
    @Query(
        """
            SELECT 
                -- TimeEntry fields
                TIMEENTRY.id AS timeEntry_id,
                TIMEENTRY.typeTimer AS timeEntry_typeTimer,
                TIMEENTRY.time AS timeEntry_time,
                TIMEENTRY.restTime AS timeEntry_restTime,
                TIMEENTRY.intervals AS timeEntry_intervals,
                TIMEENTRY.idHabit AS timeEntry_idHabit,
                TIMEENTRY.lastTimeUsed AS timeEntry_lastTimeUsed,
                TIMEENTRY.favourite AS timeEntry_favourite,
        
                -- Habit fields
                HABIT.id AS habit_id,
                HABIT.name AS habit_name,
                HABIT.description AS habit_description,
                HABIT.color AS habit_color,
                HABIT.icon AS habit_icon,
                HABIT.goal AS habit_goal,
                HABIT.unit AS habit_unit,
                HABIT.typeHabit AS habit_typeHabit
        
            FROM TIMEENTRY 
            LEFT JOIN HABIT ON TIMEENTRY.idHabit = HABIT.id
            WHERE favourite = 1
            ORDER BY TIMEENTRY.lastTimeUsed DESC
    """
    )
    fun findFavourites(): Flow<List<TimeEntryWithHabit>>

    /**
     * Streams a heavily optimized tracking queue isolating the last 5 recently modified
     * standard (non-favourite) time instruments. Used to feed the quick-history interface.
     *
     * @return A cold, reactive [Flow] tracking the recent tracking history sub-graph.
     */
    @Query(
        """
            SELECT 
                -- TimeEntry fields
                TIMEENTRY.id AS timeEntry_id,
                TIMEENTRY.typeTimer AS timeEntry_typeTimer,
                TIMEENTRY.time AS timeEntry_time,
                TIMEENTRY.restTime AS timeEntry_restTime,
                TIMEENTRY.intervals AS timeEntry_intervals,
                TIMEENTRY.idHabit AS timeEntry_idHabit,
                TIMEENTRY.lastTimeUsed AS timeEntry_lastTimeUsed,
                TIMEENTRY.favourite AS timeEntry_favourite,
        
                -- Habit fields
                HABIT.id AS habit_id,
                HABIT.name AS habit_name,
                HABIT.description AS habit_description,
                HABIT.color AS habit_color,
                HABIT.icon AS habit_icon,
                HABIT.goal AS habit_goal,
                HABIT.unit AS habit_unit,
                HABIT.typeHabit AS habit_typeHabit
        
            FROM TIMEENTRY 
            LEFT JOIN HABIT ON TIMEENTRY.idHabit = HABIT.id
            WHERE favourite = 0
            ORDER BY TIMEENTRY.lastTimeUsed DESC
            LIMIT 5
    """
    )
    fun findLastTimeEntryUsed(): Flow<List<TimeEntryWithHabit>>

    /**
     * Modifies the bookmark status and locks down the latest usage timeline checkpoint of a single entry.
     *
     * @param id The unique target primary key handle to modify.
     * @param favorite The updated boolean flag reflecting bookmark states.
     * @param lastUsed The operational date-time stamp marking this invocation loop.
     */
    @Query("""
        UPDATE TIMEENTRY SET favourite = :favorite, lastTimeUsed = :lastUsed WHERE id = :id
    """)
    fun updateFavoriteFromTimeEntry(id:Long,favorite:Boolean,lastUsed:LocalDateTime = LocalDateTime.now())

    /**
     * Drops a [TimeEntry] configuration row from the cache directory.
     *
     * @param id The target unique primary key row handle to drop.
     */
    @Query("""
        DELETE FROM TIMEENTRY WHERE id = :id
    """)
    fun deleteTimeEntry(id:Long)

}