package aeb.proyecto.stopwatch.constants

const val ACTION_SERVICE_RESUME = "ACTION_SERVICE_RESUME"
const val ACTION_SERVICE_STOP = "ACTION_SERVICE_STOP"
const val ACTION_SERVICE_CANCEL = "ACTION_SERVICE_CANCEL"
const val ACTION_SERVICE_FINISH = "ACTION_SERVICE_FINISH"

const val ACTION_SERVICE_START_STOPWATCH = "ACTION_SERVICE_STOP_STOPWATCH"
const val ACTION_SERVICE_START_TIMER = "ACTION_SERVICE_START_TIMER"
const val ACTION_SERVICE_START_INTERVAL = "ACTION_SERVICE_START_INTERVAL"

const val NOTIFICATION_CHANNEL_ID = "STOPWATCH_NOTIFICATION_ID"
const val NOTIFICATION_CHANNEL_NAME = "STOPWATCH_NOTIFICATION"

const val NOTIFICATION_ID = -900

const val CLICK_REQUEST_CODE = 100
const val CANCEL_REQUEST_CODE = 101
const val STOP_REQUEST_CODE = 102
const val RESUME_REQUEST_CODE = 103

const val STOPWATCH = 0
const val TIMER = 1
const val INTERVAL = 2