package aeb.proyecto.room.habitWithNotification

import aeb.proyecto.room.dao.HabitWithDailyHabitDao
import aeb.proyecto.room.dao.HabitWithNotificationDao
import aeb.proyecto.room.database.DatabaseHabitTracker
import aeb.proyecto.room.entities.Habit
import aeb.proyecto.room.entities.HabitNotification
import aeb.proyecto.room.entities.relations.HabitWithNotification
import aeb.proyecto.room.model.classes.TypeNotification
import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import junit.framework.TestCase.assertEquals
import junit.framework.TestCase.assertFalse
import junit.framework.TestCase.assertNotNull
import junit.framework.TestCase.assertTrue
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import java.time.LocalDate
import java.time.LocalTime

@RunWith(AndroidJUnit4::class)
@OptIn(ExperimentalCoroutinesApi::class)
class HabitWithNotificationTest {

    private lateinit var database: DatabaseHabitTracker
    private lateinit var habitWithNotificationDao: HabitWithNotificationDao

    @Before
    fun setUp() {
        val context = ApplicationProvider.getApplicationContext<Context>()

        database = Room.inMemoryDatabaseBuilder(
            context,
            DatabaseHabitTracker::class.java
        ).allowMainThreadQueries().build()

        habitWithNotificationDao = database.habitWithNotificationDao()
    }

    @After
    fun tearDown() {
        database.close()
    }

    @Test
    fun givenANewHabit_whenInsertHabitIsCalled_thenReturnsTheCorrectAutogeneratedId() = runTest {
        // --- GIVEN ---
        val newHabit = Habit(id = 0L, name = "Ir al gimnasio")

        // --- WHEN ---
        val generatedId = habitWithNotificationDao.insertHabit(newHabit)

        // --- THEN ---
        assertEquals(1L, generatedId)
    }

    @Test
    fun givenAnExistingHabit_whenUpdateHabitIsCalled_thenTheChangesArePersistedCorrectly() = runTest {
        // --- GIVEN ---
        val habitId = 10L
        val initialHabit = Habit(id = habitId, name = "Estudiar desarrollo Android")
        val updatedHabit = Habit(id = habitId, name = "Estudiar Jetpack Compose")

        habitWithNotificationDao.insertHabit(initialHabit)

        // --- WHEN ---
        habitWithNotificationDao.updateHabit(updatedHabit)

        // --- THEN ---
        val result = habitWithNotificationDao.getHabitById(habitId)
        assertNotNull(result)
        assertEquals("Estudiar Jetpack Compose", result.habit.name)
    }

    @Test
    fun givenAListOfNotifications_whenInsertNotificationsIsCalled_thenAllRecordsAreSavedSuccessfully() = runTest {
        // --- GIVEN ---
        val habitId = 1L
        val parentHabit = Habit(id = habitId, name = "Revisar notas de Dale Carnegie")

        habitWithNotificationDao.insertHabit(parentHabit)

        val notificationsList = listOf(
            HabitNotification(id = 101L, habitId = habitId,time = LocalTime.now()),
            HabitNotification(id = 102L, habitId = habitId,time = LocalTime.now().plus(1,java.time.temporal.ChronoUnit.HOURS))
        )

        // --- WHEN ---
        habitWithNotificationDao.insertNotifications(notificationsList)

        // --- THEN ---
        val savedNotifications = habitWithNotificationDao.getNotificationById(habitId)
        assertEquals(2, savedNotifications.size)
        assertTrue(savedNotifications.containsAll(notificationsList))
    }

    @Test
    fun givenExistingNotifications_whenUpdateNotificationIsCalled_thenAllRecordsAreUpdatedCorrectly() = runTest {
        // --- GIVEN ---
        val habitId = 1L
        val parentHabit = Habit(id = habitId, name = "Preparar pizza casera")
        habitWithNotificationDao.insertHabit(parentHabit)

        val initialNotification = HabitNotification(
            id = 50L,
            habitId = habitId,
            time = LocalTime.of(10, 0),
            type = TypeNotification.Recurring(1)
        )
        habitWithNotificationDao.insertNotifications(listOf(initialNotification))

        val updatedNotification = HabitNotification(
            id = 50L,
            habitId = habitId,
            time = LocalTime.of(20, 30),
            type = TypeNotification.Recurring(1)
        )

        // --- WHEN ---
        habitWithNotificationDao.updateNotification(listOf(updatedNotification))

        // --- THEN ---
        val result = habitWithNotificationDao.getNotificationById(habitId)
        assertEquals(1, result.size)
        assertEquals(LocalTime.of(20, 30), result.first().time)
    }

    @Test
    fun givenHabitWithNotifications_whenGetAllNotificationsWithIdIsCalled_thenReturnCorrectProjectionList() = runTest {
        // --- GIVEN ---
        val habitId = 2L
        val parentHabit = Habit(id = habitId, name = "Entrenar antebrazo", color = -16711936)
        habitWithNotificationDao.insertHabit(parentHabit)

        val targetTime = LocalTime.of(18, 0)
        val notification = HabitNotification(
            id = 60L,
            habitId = habitId,
            time = targetTime,
            type = TypeNotification.Recurring(1)
        )
        habitWithNotificationDao.insertNotifications(listOf(notification))

        // --- WHEN ---
        val projections = habitWithNotificationDao.getAllNotificationsWithId(habitId)

        // --- THEN ---
        assertEquals(1, projections.size)
        val projection = projections.first()
        assertEquals(60L, projection.id)
        assertEquals("Entrenar antebrazo", projection.name)
        assertEquals(-16711936, projection.color)
        assertEquals(targetTime, projection.time)
    }

    @Test
    fun givenHabitWithMultipleNotifications_whenDeleteNotificationsIsCalled_thenAllBoundNotificationsArePurged() = runTest {
        // --- GIVEN ---
        val habitId = 3L
        val parentHabit = Habit(id = habitId, name = "Leer a Dale Carnegie")
        habitWithNotificationDao.insertHabit(parentHabit)

        val notifications = listOf(
            HabitNotification(id = 71L, habitId = habitId, time = LocalTime.of(8, 0)),
            HabitNotification(id = 72L, habitId = habitId, time = LocalTime.of(22, 0))
        )
        habitWithNotificationDao.insertNotifications(notifications)

        // --- WHEN ---
        habitWithNotificationDao.deleteNotifications(habitId)

        // --- THEN ---
        val resultRelation = habitWithNotificationDao.getHabitById(habitId)
        assertNotNull(resultRelation)
        assertTrue(resultRelation.notifications.isEmpty())
    }

    @Test
    fun givenANewHabitWithNotifications_whenSaveHabitIsCalled_thenInsertsParentAndBindsAutogeneratedIdToAllChildren() = runTest {
        // --- GIVEN ---
        val newHabit = Habit(id = 0L, name = "Entrenar bíceps")
        val notification1 = HabitNotification(id = 0L, habitId = 0L, time = LocalTime.of(9, 0))
        val notification2 = HabitNotification(id = 0L, habitId = 0L, time = LocalTime.of(21, 0))

        val aggregate = HabitWithNotification(
            habit = newHabit,
            notifications = mutableListOf(notification1, notification2)
        )

        // --- WHEN ---
        val generatedId = habitWithNotificationDao.saveHabit(aggregate)

        // --- THEN ---
        assertEquals(1L, generatedId)

        val databaseResult = habitWithNotificationDao.getHabitById(generatedId)
        assertNotNull(databaseResult)
        assertEquals(2, databaseResult.notifications.size)

        assertTrue(databaseResult.notifications.all { it.habitId == generatedId })
    }

    @Test
    fun givenANewHabitWithoutNotifications_whenSaveHabitIsCalled_thenInsertsParentSafelyAndLeavesNotificationsEmpty() = runTest {
        // --- GIVEN ---
        val standaloneHabit = Habit(id = 0L, name = "Hacer pizza casera")
        val aggregate = HabitWithNotification(habit = standaloneHabit, notifications = mutableListOf())

        // --- WHEN ---
        val generatedId = habitWithNotificationDao.saveHabit(aggregate)

        // --- THEN ---
        val databaseResult = habitWithNotificationDao.getHabitById(generatedId)
        assertNotNull(databaseResult)
        assertEquals("Hacer pizza casera", databaseResult.habit.name)
        assertTrue(databaseResult.notifications.isEmpty())
    }

    @Test
    fun givenAnExistingHabitWithOldNotifications_whenUpdateHabitIsCalled_thenPurgesLegacyRecordsAndOverridesWithNewGraph() = runTest {
        // --- GIVEN ---
        val habitId = 42L
        val initialHabit = Habit(id = habitId, name = "Ajustar rutina")

        val oldNotifications = listOf(
            HabitNotification(id = 201L, habitId = habitId, time = LocalTime.of(7, 0)),
            HabitNotification(id = 202L, habitId = habitId, time = LocalTime.of(14, 0))
        )
        habitWithNotificationDao.insertHabit(initialHabit)
        habitWithNotificationDao.insertNotifications(oldNotifications)

        val updatedHabit = Habit(id = habitId, name = "Rutina Optimizada")
        val newNotification = HabitNotification(id = 300L, habitId = habitId, time = LocalTime.of(19, 0))

        val updateAggregate = HabitWithNotification(
            habit = updatedHabit,
            notifications = mutableListOf(newNotification)
        )

        // --- WHEN ---
        val returnedId = habitWithNotificationDao.updateHabit(updateAggregate)

        // --- THEN ---
        assertEquals(habitId, returnedId)

        val finalState = habitWithNotificationDao.getHabitById(habitId)
        assertNotNull(finalState)
        assertEquals("Rutina Optimizada", finalState.habit.name)

        assertEquals(1, finalState.notifications.size)
        assertEquals(LocalTime.of(19, 0), finalState.notifications.first().time)

        val allNotificationsInDb = habitWithNotificationDao.getNotificationById(habitId)
        assertFalse(allNotificationsInDb.any { it.id == 201L || it.id == 202L })
    }

    @Test
    fun givenAnExistingHabitWithNotifications_whenUpdateHabitIsCalledWithEmptyList_thenRemovesAllRemindersFromDatabase() = runTest {
        // --- GIVEN ---
        val habitId = 99L
        val parentHabit = Habit(id = habitId, name = "Leer antes de dormir")
        val reminder = HabitNotification(id = 500L, habitId = habitId, time = LocalTime.of(23, 0))

        habitWithNotificationDao.insertHabit(parentHabit)
        habitWithNotificationDao.insertNotifications(listOf(reminder))

        val clearNotificationsAggregate = HabitWithNotification(
            habit = parentHabit,
            notifications = mutableListOf()
        )

        // --- WHEN ---
        habitWithNotificationDao.updateHabit(clearNotificationsAggregate)

        // --- THEN ---
        val finalState = habitWithNotificationDao.getHabitById(habitId)
        assertNotNull(finalState)
        assertTrue(finalState.notifications.isEmpty())
    }
}