package aeb.proyecto.room.timeEntry

import aeb.proyecto.room.dao.HabitWithNotificationDao
import aeb.proyecto.room.dao.TimerEntryDao
import aeb.proyecto.room.database.DatabaseHabitTracker
import aeb.proyecto.room.entities.Habit
import aeb.proyecto.room.entities.TimeEntry
import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import app.cash.turbine.test
import junit.framework.TestCase.assertEquals
import junit.framework.TestCase.assertFalse
import junit.framework.TestCase.assertNotNull
import junit.framework.TestCase.assertNull
import junit.framework.TestCase.assertTrue
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import java.time.LocalDate
import java.time.LocalDateTime

@RunWith(AndroidJUnit4::class)
@OptIn(ExperimentalCoroutinesApi::class)
class TimeEntryDaoTest {

    private lateinit var database: DatabaseHabitTracker
    private lateinit var timeEntryDao: TimerEntryDao
    private lateinit var habitWithNotificationDao: HabitWithNotificationDao

    @Before
    fun setUp() {
        val context = ApplicationProvider.getApplicationContext<Context>()

        database = Room.inMemoryDatabaseBuilder(
            context,
            DatabaseHabitTracker::class.java
        ).allowMainThreadQueries().build()

        timeEntryDao = database.timerEntryDao()
        habitWithNotificationDao = database.habitWithNotificationDao()
    }

    @After
    fun tearDown() {
        database.close()
    }

    @Test
    fun givenANewTimeEntry_whenInsertTimerEntryIsCalled_thenReturnsTheCorrectAutogeneratedId() = runTest {
        // --- GIVEN ---
        val newEntry = TimeEntry(
            id = 0L,
            typeTimer = 1,
            time = 1500L,
            restTime = 300L,
            intervals = 4L,
            idHabit = null,
            lastTimeUsed = LocalDateTime.now(),
            favourite = false
        )

        // --- WHEN ---
        val generatedId = timeEntryDao.insertTimerEntry(newEntry)

        // --- THEN ---
        assertEquals(1L, generatedId)
    }

    @Test
    fun givenAnExistingTimeEntry_whenUpdateTimerEntryIsCalled_thenAllChangesArePersistedCorrectly() = runTest {
        // --- GIVEN ---
        val entryId = 42L
        val initialEntry = TimeEntry(
            id = entryId,
            typeTimer = 1,
            time = 600L,
            restTime = 60L,
            favourite = false
        )

        timeEntryDao.insertTimerEntry(initialEntry)

        val updatedEntry = initialEntry.copy(
            time = 900L,
            lastTimeUsed = LocalDateTime.now()
        )

        // --- WHEN ---
        timeEntryDao.updateTimerEntry(updatedEntry)

        // --- THEN ---
        timeEntryDao.findLastTimeEntryUsed().test {
            val currentEmission = awaitItem()

            assertNotNull(currentEmission)
            assertEquals(1, currentEmission.size)

            val verifiedEntry = currentEmission.first().timeEntry
            assertEquals(entryId, verifiedEntry.id)
            assertEquals(900L, verifiedEntry.time)
            assertFalse(verifiedEntry.favourite)

            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun givenAnExistingStopWatchWithoutHabit_whenFindStopWatchIsCalledWithNull_thenReturnTheCorrectTimeEntry() = runTest {
        // --- GIVEN ---
        val expectedEntry = TimeEntry(id = 1L, typeTimer = 0, idHabit = null)
        timeEntryDao.insertTimerEntry(expectedEntry)

        // --- WHEN ---
        val result = timeEntryDao.findStopWatch(idHabit = null)

        // --- THEN ---
        assertNotNull(result)
        assertEquals(1L, result?.id)
        assertNull(result?.idHabit)
    }

    @Test
    fun givenAnExistingStopWatchWithHabit_whenFindStopWatchIsCalledWithMatchingId_thenReturnTheCorrectTimeEntry() = runTest {
        // --- GIVEN ---
        val habitId = 10L
        val expectedEntry = TimeEntry(id = 2L, typeTimer = 0, idHabit = habitId)

        // --- WHEN ---
        habitWithNotificationDao.insertHabit(Habit(id = habitId))

        timeEntryDao.insertTimerEntry(expectedEntry)
        val result = timeEntryDao.findStopWatch(idHabit = habitId)

        // --- THEN ---
        assertNotNull(result)
        assertEquals(habitId, result?.idHabit)
    }

    @Test
    fun givenMatchingTimeAndHabitId_whenFindTimerIsCalled_thenReturnTheCorrectTimeEntry() = runTest {
        // --- GIVEN ---
        val targetTime = 1200L
        val habitId = 5L
        val expectedEntry = TimeEntry(id = 3L, typeTimer = 1, time = targetTime, idHabit = habitId)

        // --- WHEN ---
        habitWithNotificationDao.insertHabit(Habit(id = habitId))

        timeEntryDao.insertTimerEntry(expectedEntry)
        val result = timeEntryDao.findTimer(time = targetTime, idHabit = habitId)

        // --- THEN ---
        assertNotNull(result)
        assertEquals(targetTime, result?.time)
        assertEquals(habitId, result?.idHabit)
    }

    @Test
    fun givenCorrectTimeButDifferentHabitId_whenFindTimerIsCalled_thenReturnNull() = runTest {
        // --- GIVEN ---
        val targetTime = 1200L
        val savedEntry = TimeEntry(id = 4L, typeTimer = 1, time = targetTime)

        timeEntryDao.insertTimerEntry(savedEntry)

        // --- WHEN ---
        val result = timeEntryDao.findTimer(time = targetTime, idHabit = 999L)

        // --- THEN ---
        assertNull(result)
    }

    @Test
    fun givenMatchingIntervalParameters_whenFindIntervalIsCalled_thenReturnTheCorrectTimeEntry() = runTest {
        // --- GIVEN ---
        val expectedEntry = TimeEntry(
            id = 5L,
            typeTimer = 2,
            time = 45L,      // 45s de racha de alta intensidad
            restTime = 15L,  // 15s de descanso
            intervals = 8L,  // 8 series (Tabata completo)
            idHabit = null
        )
        timeEntryDao.insertTimerEntry(expectedEntry)

        // --- WHEN ---
        val result = timeEntryDao.findInterval(time = 45L, rest = 15L, interval = 8L, idHabit = null)

        // --- THEN ---
        assertNotNull(result)
        assertEquals(45L, result?.time)
        assertEquals(15L, result?.restTime)
        assertEquals(8L, result?.intervals)
    }

    @Test
    fun givenIncorrectIntervalLoopsCount_whenFindIntervalIsCalled_thenReturnNull() = runTest {
        // --- GIVEN ---
        val savedEntry = TimeEntry(id = 6L, typeTimer = 2, time = 30L, restTime = 10L, intervals = 5L, idHabit = null)
        timeEntryDao.insertTimerEntry(savedEntry)

        // --- WHEN ---
        val result = timeEntryDao.findInterval(time = 30L, rest = 10L, interval = 10L, idHabit = null)

        // --- THEN ---
        assertNull(result)
    }

    @Test
    fun givenMixedTimeEntries_whenFindFavouritesIsCalled_thenReturnOnlyEntriesWithFavouriteTrueOrderedByLastTimeUsed() = runTest {
        // --- GIVEN ---
        val baseTime = LocalDateTime.now()

        val entryNotFavourite = TimeEntry(id = 1L, typeTimer = 1, favourite = false, lastTimeUsed = baseTime)
        val entryFavOld = TimeEntry(id = 2L, typeTimer = 1, favourite = true, lastTimeUsed = baseTime.minusDays(1))
        val entryFavNew = TimeEntry(id = 3L, typeTimer = 2, favourite = true, lastTimeUsed = baseTime)

        timeEntryDao.insertTimerEntry(entryNotFavourite)
        timeEntryDao.insertTimerEntry(entryFavOld)
        timeEntryDao.insertTimerEntry(entryFavNew)

        // --- WHEN & THEN ---
        timeEntryDao.findFavourites().test {
            val currentEmission = awaitItem()

            assertNotNull(currentEmission)
            assertEquals(2, currentEmission.size)

            assertEquals(3L, currentEmission[0].timeEntry.id)
            assertEquals(2L, currentEmission[1].timeEntry.id)

            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun givenMultipleNonFavouriteEntries_whenFindLastTimeEntryUsedIsCalled_thenReturnAtMostFiveEntriesOrderedByRecentUse() = runTest {
        // --- GIVEN ---
        val baseTime = LocalDateTime.now()

        val favouriteEntry = TimeEntry(id = 100L, typeTimer = 1, favourite = true, lastTimeUsed = baseTime)
        timeEntryDao.insertTimerEntry(favouriteEntry)

        for (i in 1..6) {
            val entry = TimeEntry(
                id = i.toLong(),
                typeTimer = 0,
                favourite = false,
                lastTimeUsed = baseTime.plusMinutes(i.toLong())
            )
            timeEntryDao.insertTimerEntry(entry)
        }

        // --- WHEN & THEN ---
        timeEntryDao.findLastTimeEntryUsed().test {
            val currentEmission = awaitItem()

            assertNotNull(currentEmission)
            assertEquals(5, currentEmission.size)

            assertTrue(currentEmission.none { it.timeEntry.favourite })

            assertEquals(6L, currentEmission.first().timeEntry.id)
            assertEquals(2L, currentEmission.last().timeEntry.id)

            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun givenAnExistingTimeEntry_whenUpdateFavoriteFromTimeEntryIsCalled_thenChangesArePersistedCorrectly() = runTest {
        // --- GIVEN ---
        val entryId = 77L
        val initialEntry = TimeEntry(
            id = entryId,
            typeTimer = 0,
            favourite = false,
            lastTimeUsed = LocalDateTime.now().minusDays(5)
        )
        timeEntryDao.insertTimerEntry(initialEntry)

        val targetTime = LocalDateTime.now()

        // --- WHEN ---
        timeEntryDao.updateFavoriteFromTimeEntry(
            id = entryId,
            favorite = true,
            lastUsed = targetTime
        )

        // --- THEN ---
        timeEntryDao.findFavourites().test {
            val currentEmission = awaitItem()

            assertNotNull(currentEmission)
            assertEquals(1, currentEmission.size)

            val updatedEntry = currentEmission.first().timeEntry
            assertEquals(entryId, updatedEntry.id)
            assertTrue(updatedEntry.favourite)
            assertEquals(targetTime, updatedEntry.lastTimeUsed)

            cancelAndIgnoreRemainingEvents()
        }
    }

    @Test
    fun givenAnExistingTimeEntry_whenDeleteTimeEntryIsCalled_thenRowIsRemovedFromDatabase() = runTest {
        // --- GIVEN ---
        val entryId = 99L
        val entry = TimeEntry(id = entryId, typeTimer = 0, idHabit = null)
        timeEntryDao.insertTimerEntry(entry)

        val beforeDelete = timeEntryDao.findStopWatch(idHabit = null)
        assertNotNull(beforeDelete)
        assertEquals(entryId, beforeDelete?.id)

        // --- WHEN ---
        timeEntryDao.deleteTimeEntry(id = entryId)

        // --- THEN ---
        val afterDelete = timeEntryDao.findStopWatch(idHabit = null)

        assertNull(afterDelete)
    }
}