package aeb.proyecto.room.converters

import androidx.compose.material.icons.Icons
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.room.TypeConverter

/**
 * Dynamic reflection-driven persistence bridge linking vector assets to scalar string tokens.
 *
 * This marshaller bypasses boilerplate lookup tables by resolving Compose Icon Kotlin singletons
 * via runtime class loading using [Class.forName].
 * * CRITICAL PRODUCTION NOTE: Because this class relies on exact string signatures to locate
 * compiler-generated Icon extension classes at runtime, it requires strict minification rules.
 * The ProGuard/R8 lines appended below MUST be active in your 'proguard-rules.pro' file
 * to prevent the compiler from stripping or renaming the Material Icons codebase in release builds.
 */
class IconConverter {

    /**
     * Extracts the canonical short name signature from an [ImageVector] container.
     *
     * Example: Maps "Filled.AccessTime" and returns the flat string string "AccessTime".
     *
     * @param imageVector The active vector layout token present in memory.
     * @return The flat string name descriptor representing the icon asset.
     */
    @TypeConverter
    fun fromImageVector(imageVector: ImageVector): String = imageVector.name.split(".")[1]

    /**
     * Resolves and reinstantiates an [ImageVector] instance via Java Reflection using its serialized string descriptor.
     *
     * Locates the autogenerated target extension file class mapping the requested icon string inside
     * the Jetpack Compose Material Icons framework layer.
     *
     * @param value The raw scalar string identifier pointing to an icon asset (e.g., "Timer").
     * @return The dynamically resolved type-safe [ImageVector] mapping back to the framework singleton.
     */
    @TypeConverter
    fun toImageVector(value:String): ImageVector {
        val cl = Class.forName("androidx.compose.material.icons.filled.${value}Kt")
        val method = cl.declaredMethods.first()
        return method.invoke(null, Icons.Filled) as ImageVector
    }
}

// ===================================================================================================
// REQUIRED PROGUARD/R8 RULES FOR PRODUCTION RELEASE
// ===================================================================================================
// Copy and paste the following rules inside your project's 'proguard-rules.pro' file:
//
// # Conservar los nombres de las clases de iconos y sus métodos de extensión para la reflexión de Room
// -keep class androidx.compose.material.icons.filled.** { *; }
// -keep class androidx.compose.material.icons.automirrored.filled.** { *; }
// ===================================================================================================