package aeb.proyecto.room.repository

import aeb.proyecto.room.dao.HabitWithDailyHabitDao
import aeb.proyecto.room.entities.Habit
import aeb.proyecto.room.entities.HabitDay
import aeb.proyecto.room.entities.relations.HabitWithDailyHabit
import aeb.proyecto.room.entities.relations.HabitWithDay
import aeb.proyecto.room.model.classes.listTime
import android.util.Log
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.map
import java.math.BigDecimal
import java.time.LocalDate
import javax.inject.Inject

/**
 * Domain-facing repository managing the business rules, filtering pipelines, and reactive
 * aggregation logic for habits and their operational tracking histories.
 *
 * Acts as an intermediate data broker layer that harnesses reactive stream combinations ([combine])
 * and custom mappings to deliver granular, component-ready state layouts to the presentation layers.
 *
 * @property habitWithDailyHabitDao The primary localized data storage engine access point.
 */
class HabitWithDailyHabitRepo @Inject constructor(
    private val habitWithDailyHabitDao: HabitWithDailyHabitDao
) {

    /**
     * Persists a newly established [Habit] blueprint target.
     *
     * @param habit The structural metadata layout container.
     * @return The autogenerated unique primary key [Long] registry handle.
     */
    fun insert(habit: Habit): Long  {
        return habitWithDailyHabitDao.insertHabit(habit)
    }

    /**
     * Registers a new localized execution cell logging active user progress.
     *
     * @param dailyHabit The metric log payload bound to a specific calendar checkpoint.
     * @return The unique primary key handle assigned to the tracking log row.
     */
    fun insertDailyHabit(dailyHabit: HabitDay): Long {
        return habitWithDailyHabitDao.insertDailyHabit(dailyHabit)
    }

    /**
     * Modifies the primary identity configurations of a registered [Habit].
     */
    fun updateHabit(habit: Habit) {
        habitWithDailyHabitDao.updateHabit(habit)
    }

    /**
     * Modifies the quantitative metrics or execution states of an active [HabitDay] tracking cell.
     */
    fun updateDailyHabit(dailyHabit: HabitDay) {
        habitWithDailyHabitDao.updateDailyHabit(dailyHabit)
    }

    /**
     * Drop a [Habit] record from the local database ecosystem. Cascading rules handle relational purges.
     */
    fun deleteHabit(habitId: Long) {
        habitWithDailyHabitDao.deleteHabit(habitId)
    }

    /**
     * Performs a snapshot lookup capturing historical completion logs bound to a specific habit timeline.
     */
    fun getDailyHabits(id: Long): List<HabitDay> {
        return habitWithDailyHabitDao.getDailyHabits(id)
    }

    /**
     * Emits a reactive stream tracking the entire combined graph array of habits paired with all historical day logs.
     */
    fun getHabits(): Flow<List<HabitWithDailyHabit>> {
        return habitWithDailyHabitDao.getHabits()
    }

    /**
     * Synchronously resolves an isolated day tracking block mapping an exact date and parent checkpoint.
     */
    fun getHabitDay(date: LocalDate, idHabit: Long): HabitDay? {
        return habitWithDailyHabitDao.getHabitDay(date, idHabit)
    }

    /**
     * Transforms and streams active habit structures down to a distinct, flat list of their canonical string tags.
     * Filters duplicate instances to feed categorized dashboard user selection chips.
     *
     * @return A cold stream emitting unique string metadata tags.
     */
    fun getExistingTypesHabit():Flow<List<String>>{
        return habitWithDailyHabitDao.getExistingTypesHabit()
            .map { types ->
                types
                    .distinctBy { it::class }
                    .map { it.tag }
            }
    }

    /**
     * Combines, filters, and slices separate entity streams on-the-fly to construct a reactive timeline
     * aggregate matching a chosen calendar range window and explicit cadence classification.
     *
     * @param startDate The lower bounds inclusive calendar fence.
     * @param endDate The upper bounds inclusive calendar fence.
     * @param tag The target unique discriminator string mapping to specific [TypeHabit] blueprints.
     * @return A hot stream compiling synchronized, fully populated structural relation lists.
     */
    fun getHabitWithDailyHabitsByDateAndType(startDate: LocalDate, endDate: LocalDate, tag:String): Flow<List<HabitWithDailyHabit>> {
        return combine(
            habitWithDailyHabitDao.getAllHabits(),
            habitWithDailyHabitDao.getDailyHabitsByDateRange(startDate, endDate)
        ) { habits, filteredDays ->
            habits
                .filter { it.typeHabit.tag == tag }
                .map { habit ->
                    val daysForHabit = filteredDays.filter { it.idHabit == habit.id }
                    HabitWithDailyHabit(habit = habit, dailyHabits = daysForHabit.toMutableList())
                }
        }
    }

    /**
     * Combines distinct reactive flows to dynamically reconstruct a focused, localized history matrix
     * tracking a solitary habit target across a specified calendar date range window.
     *
     * @param id The unique parent metadata primary key identifier.
     * @param startDate The lower bounds calendar fence boundary.
     * @param endDate The upper bounds calendar fence boundary.
     * @return A reactive stream yielding the consolidated relation snapshot, or null if dropped upstream.
     */
    fun getHabitWithDailyHabitsByDateToDate(id:Long, startDate: LocalDate, endDate: LocalDate): Flow<HabitWithDailyHabit?>{
        return combine(
            habitWithDailyHabitDao.getHabitFlow(id),
            habitWithDailyHabitDao.getDailyHabitsByDateRangeById(id,startDate,endDate)
        ) { habit, dailyHabits ->
            habit?.let {
                HabitWithDailyHabit(habit = habit, dailyHabits = dailyHabits.toMutableList())
            }
        }
    }

    /**
     * Fetches a raw, synchronous configuration snapshot of an active habit row.
     */
    fun getHabit(id:Long):Habit{
        return habitWithDailyHabitDao.getHabit(id)
    }

    /**
     * Hard drops an isolated logging day slot matching an explicit date point.
     */
    fun deleteHabitDay(id:Long,date:LocalDate){
        habitWithDailyHabitDao.deleteHabitDay(id,date)
    }

    /**
     * High-performance synthesis query pulling configuration states and specific calendar logs.
     * Safely constructs a zero-progress baseline model if no entry has been written for that date space yet.
     *
     * @return A robust [HabitWithDay] state object ready for dashboard UI widget rendering steps.
     */
    fun getHabitWithDay(id:Long,date:LocalDate): HabitWithDay {
        val habit = habitWithDailyHabitDao.getHabit(id)
        val day = habitWithDailyHabitDao.getDayByDate(id,date) ?: HabitDay(date = date, idHabit = id, goalDone = BigDecimal(0))

        return HabitWithDay(habit, day)
    }

    /**
     * Defensive synthesis query matching [getHabitWithDay], but adding safety bounds that
     * return null gracefully if the parent identity has been wiped out of the repository tree.
     */
    fun getHabitWithDayOrNull(id:Long,date:LocalDate): HabitWithDay? {
        val habit = habitWithDailyHabitDao.getHabitOrNull(id)

        if(habit != null){
            val day = habitWithDailyHabitDao.getDayByDate(id,date) ?: HabitDay(date = date, idHabit = id, goalDone = BigDecimal(0))
            return HabitWithDay(habit, day)
        }

        return null
    }

    /**
     * Streams an isolated collection containing only habits explicitly structured around temporal metric rules.
     */
    fun getHabitWithTimeUnit():Flow<List<Habit>>{
        return habitWithDailyHabitDao.getAllHabits()
            .map { habits ->
                habits.filter { it.unit in listTime }
            }
    }

    /**
     * Streams all active core [Habit] database entries available in the architecture.
     */
    fun getAllHabits(): Flow<List<Habit>>{
        return habitWithDailyHabitDao.getAllHabits()
    }

    /**
     * Streams a singular aggregated relation mapping a targeted parent identity block.
     */
    fun getHabitWithDailyHabit(id:Long): Flow<HabitWithDailyHabit?>{
        return habitWithDailyHabitDao.getHabitWithDailyHabits(id)
    }

}

