package aeb.proyecto.room.repository

import aeb.proyecto.room.dao.HabitWithNotificationDao
import aeb.proyecto.room.entities.HabitNotification
import aeb.proyecto.room.entities.relations.HabitWithNotification
import aeb.proyecto.room.model.NotificationWithNameAndColor
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Singleton-scoped repository coordinating configuration and notification management lifecycles
 * for individual habit alert architectures.
 *
 * This layer abstracts complex multi-row entity orchestration loops, providing clean entry points
 * for view models to trigger atomic transactional persistence updates on the underlying cache.
 *
 * @property habitWithNotificationDao Core Data Access Object managing localized database alert states.
 */
@Singleton
class HabitWithNotificacionRepo @Inject constructor(
    private val habitWithNotificationDao: HabitWithNotificationDao
) {

    /**
     * Commits a brand new [HabitWithNotification] aggregate graph into the database layer.
     *
     * It maps metadata and bridges child foreign keys safely within a singular atomic transaction wrapper.
     *
     * @param habitWithNotification The relational compound aggregate structure to persist.
     * @return The unique autogenerated primary key [Long] assigned to the root habit entry.
     */
    fun insertHabit(habitWithNotification: HabitWithNotification):Long{
        return habitWithNotificationDao.saveHabit(habitWithNotification)
    }

    /**
     * Updates an existing [HabitWithNotification] aggregate graph by executing an atomic
     * "Wipe & Re-insert" cascading strategy over its nested alert records.
     *
     * @param habitWithNotification The relational compound aggregate structure containing the modified states.
     * @return The unique immutable primary key handle [Long] identifying the modified habit entity tree.
     */
    fun updateHabit(habitWithNotification: HabitWithNotification):Long{
        return habitWithNotificationDao.updateHabit(habitWithNotification)
    }

    /**
     * Performs a synchronous relational lookup to fetch an isolated habit aggregate along with
     * its corresponding notification sub-graph.
     *
     * @param id The unique primary key handle targeting the source habit.
     * @return The fully hydrated [HabitWithNotification] relational compound entity container.
     */
    fun getHabitById(id:Long): HabitWithNotification {
        return habitWithNotificationDao.getHabitById(id)
    }

    /**
     * Performs a localized snapshot query extracting raw, non-joined [HabitNotification] rows
     * that belong to a single parent habit handle.
     *
     * @param id The target parent foreign key identifier.
     * @return A flat [List] containing matching raw alert configuration parameters.
     */
    fun getNotificationById(id:Long):List<HabitNotification>{
        return habitWithNotificationDao.getNotificationById(id)
    }

    /**
     * Fetches tabular inner-join projections mapping active notification channels alongside basic parent
     * habit features (name, color) scoped to a targeted identity check.
     *
     * Primarily utilized to refresh OS [AlarmManager] configurations when updating a single habit's schedules.
     *
     * @param id The unique parent primary key identifier.
     * @return A flat [List] of custom projection metadata objects matching the targeted habit criteria.
     */
    fun getAllNotificationsWithId(id:Long):List<NotificationWithNameAndColor>{
        return habitWithNotificationDao.getAllNotificationsWithId(id)
    }

}